### ISSUE TITLE
misspelling  confmanager/lang/de/lang.php: Schlüßel

### ISSUE THREAD

**Issue by ParoTheParrot** [cosmocode/confmanager#29]
Line 48: $lang['key'] = 'Schlüßel';

correct: 'Schlüssel'

**Comment by splitbrain** [comment]
At http://translate.dokuwiki.org/?lang=de you can help to correct it.

**Comment by ParoTheParrot** [comment]
done

**Comment by splitbrain** [comment]
thanks
