### ISSUE TITLE
Interwiki SVG oversized

### ISSUE THREAD

**Issue by nesetril** [cosmocode/confmanager#56]
SVG preview in interwiki is really big:

![image](https://user-images.githubusercontent.com/21980999/236466822-aad5abf3-3327-4cd5-9a6c-155ab9e60106.png)

**Comment by Klap-in** [comment]
Hi @nesetril I opened a PR to fix this.

**Comment by nesetril** [comment]
Till the pull request is merged, I have fixed it by adding `table img {max-width: 3vw; }`  to `conf/userall.css`.
